package entity;
// Generated 2019-2-23 22:29:09 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * TbRoomWater generated by hbm2java
 */
public class TbRoomWater implements java.io.Serializable {

	private Integer id;
	//private TbRoom tbRoom;
	private TbRoom tbRoom;
	private String water;
	private Date date;

	public TbRoomWater() {
	}

	public TbRoomWater(TbRoom tbRoom, String water, Date date) {
		this.tbRoom = tbRoom;
		this.water = water;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	

	public TbRoom getTbRoom() {
		return tbRoom;
	}

	public void setTbRoom(TbRoom tbRoom) {
		this.tbRoom = tbRoom;
	}

	public String getWater() {
		return this.water;
	}

	public void setWater(String water) {
		this.water = water;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
