package entity;
// Generated 2019-2-23 22:29:09 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbRoom generated by hbm2java
 */
public class TbRoom implements java.io.Serializable {

	private Integer id;
	private String room;
	private String address;
	private Set<TbSt> tbSts = new HashSet<TbSt>(0);
	private Set<TbRoomWater> tbRoomWaters = new HashSet<TbRoomWater>(0);

	public TbRoom() {
	}

	public TbRoom(String room, String address, Set<TbSt> tbSts,Set<TbRoomWater> tbRoomWaters) {
		this.room = room;
		this.address = address;
		this.tbSts = tbSts;
		this.tbRoomWaters=tbRoomWaters;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set<TbSt> getTbSts() {
		return this.tbSts;
	}

	public void setTbSts(Set<TbSt> tbSts) {
		this.tbSts = tbSts;
	}

	public Set<TbRoomWater> getTbRoomWaters() {
		return tbRoomWaters;
	}

	public void setTbRoomWaters(Set<TbRoomWater> tbRoomWaters) {
		this.tbRoomWaters = tbRoomWaters;
	}

}
