package entity;
// Generated 2019-2-23 22:29:09 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * TbWaterCycle generated by hbm2java
 */
public class TbWaterCycle implements java.io.Serializable {

	private Integer id;
	private Date date;

	public TbWaterCycle() {
	}

	public TbWaterCycle(Date date) {
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
